### Лабораторная работа 1

Средствами библиотеки numpy сгенерировать матрицу. Найти и вычесть из каждого столбца его среднее значение.

In [4]:
import numpy as np

In [6]:
A = np.random.randint(1, 10, (5, 5))
A

array([[3, 8, 2, 4, 1],
       [7, 4, 8, 2, 1],
       [6, 9, 9, 2, 3],
       [8, 5, 8, 9, 3],
       [3, 8, 6, 8, 6]], dtype=int32)

In [7]:
mean_columns = np.mean(A, axis=0)
mean_columns

array([5.4, 6.8, 6.6, 5. , 2.8])

In [8]:
B = A - mean_columns
B

array([[-2.4,  1.2, -4.6, -1. , -1.8],
       [ 1.6, -2.8,  1.4, -3. , -1.8],
       [ 0.6,  2.2,  2.4, -3. ,  0.2],
       [ 2.6, -1.8,  1.4,  4. ,  0.2],
       [-2.4,  1.2, -0.6,  3. ,  3.2]])